### PR TITLE
More compact code

### PR DESCRIPTION
**Pull request by flesciamento**
proposing a more compact code than the original - not tested yet

### CODE REVIEW

**Comment by morrolinux** [comment]
Could not work for multiple reasons (but correct me if I'm wrong):
1) The value of $isPenHovering could be virtually any number != 0 , it just depends on the Pen Model ID signature, therefore we can't use its direct value as a "toggle" bit for `xinput set-prop` as it's just accepting 0 or 1
2) The logic itself is quite the opposite of what you did:
Even if 1) wasn't a thing, using $isPenHovering as a toggle bit for `xinput set-prop` would result in touchscreen being enabled when the pen is overing, and touchscreen being disabled while the pen is off the screen.

**Comment by flesciamento** [comment]
Thanks for your comment. 
For 2) I used "not" operator at $isPenHovering 
For 1) if we can't use its direct value as a "toggle" bit, my propose is to use: ($isPenHovering != 0) instead.

**Comment by flesciamento** [comment]
No problem, I think that the readability is subjective because I prefer compatted code (also I guess this improve performance too), but chose is yours.
Thanks to you, I'm italian though. XD

**Comment by morrolinux** [comment]
Good to hear that bro 👍 ^^
Ciao

**Pull request closed without merging**
